name: Deploy to IIS

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Template_Web.Server/Template_Web.Server.csproj --configuration Release --framework net8.0 --output ./publish --runtime win-x86 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=false
        
      - name: Test with .NET
        run: dotnet test
        
      - name: Deploy to IIS
        uses: ChristopheLav/iis-deploy@v1
        with:
          website-name: 'yadmarzan-001-site1'
          msdeploy-service-url: 'https://win5239.site4now.net:8172/MsDeploy.axd?site=yadmarzan-001-site1'
          msdeploy-username: 'yadmarzan-001'
          msdeploy-password: 'yadshad8266'
          source-path: './publish'
          IncludeAcls: true
          

      

